In [3]:
import numpy
print('numpy.random is a {}'.format(type(numpy.random)))

numpy.random is a <class 'module'>


In [4]:
print('It contains names such as', dir(numpy.random))

It contains names such as ['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bounded_integers', '_common', '_generator', '_mt19937', '_pcg64', '_philox', '_pickle', '_sfc64', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 

In [9]:
## now calling a function in random module will require two dots
rolls = numpy.random.randint(low = 1, high = 6, size = 10)
print(rolls)
print(type(rolls))

[2 5 3 4 2 1 3 2 5 2]
<class 'numpy.ndarray'>


In [11]:
print(rolls.tolist())

[2, 5, 3, 4, 2, 1, 3, 2, 5, 2]


In [15]:
## error..cannot concatenate list to int
[3,2,5,1] + 10

TypeError: can only concatenate list (not "int") to list

In [16]:
##arrays in numpy module allow such addition
rolls + 10

array([12, 15, 13, 14, 12, 11, 13, 12, 15, 12])

In [17]:
# At which indices are the dice more than or equal to 3?
rolls >= 3

array([False,  True,  True,  True, False, False,  True, False,  True,
       False])

In [19]:
xlist = [[1,2,3], [4,5,6]]
## creating 2d array
x = numpy.asarray(xlist)
print('xlist : {}\nx : {}'.format(xlist,x))

xlist : [[1, 2, 3], [4, 5, 6]]
x : [[1 2 3]
 [4 5 6]]


In [20]:
## indexing in array
x[1,-1]

6

In [22]:
## indexing in nested list
xlist[1][-1]

6

In [25]:
!pip install tensorflow

     |████████████████████████████████| 175.5 MB 8.6 kB/s eta 0:00:01
     |████████████████████████████████| 3.3 MB 26 kB/s eta 0:00:013
     |████████████████████████████████| 57 kB 4.4 kB/s eta 0:00:02
     |████████████████████████████████| 3.0 MB 64 kB/s eta 0:00:012
     |████████████████████████████████| 42 kB 241 kB/s eta 0:00:01
     |████████████████████████████████| 15.3 MB 26 kB/s eta 0:00:011
     |████████████████████████████████| 65 kB 215 kB/s eta 0:00:01
     |████████████████████████████████| 127 kB 168 kB/s eta 0:00:01
     |████████████████████████████████| 1.0 MB 128 kB/s eta 0:00:01     |███████████████████████████████▏| 993 kB 128 kB/s eta 0:00:01
     |████████████████████████████████| 10.6 MB 229 kB/s eta 0:00:01
Processing /Users/sachinsingh/Library/Caches/pip/wheels/5f/fd/9e/b6cf5890494cb8ef0b5eaff72e5d55a70fb56316007d6dfe73/wrapt-1.12.1-cp38-cp38-macosx_10_9_x86_64.whl
     |████████████████████████████████| 462 kB 85 kB/s eta 0:00:011
     |████████████████

In [ ]:
import tensorflow as tf
print('success')

In [6]:
!pip3 uninstall tensorflow

Found existing installation: tensorflow 2.4.0
Uninstalling tensorflow-2.4.0:
  Would remove:
    /Users/sachinsingh/miniconda3/envs/NB_874/bin/estimator_ckpt_converter
    /Users/sachinsingh/miniconda3/envs/NB_874/bin/import_pb_to_tensorboard
    /Users/sachinsingh/miniconda3/envs/NB_874/bin/saved_model_cli
    /Users/sachinsingh/miniconda3/envs/NB_874/bin/tensorboard
    /Users/sachinsingh/miniconda3/envs/NB_874/bin/tf_upgrade_v2
    /Users/sachinsingh/miniconda3/envs/NB_874/bin/tflite_convert
    /Users/sachinsingh/miniconda3/envs/NB_874/bin/toco
    /Users/sachinsingh/miniconda3/envs/NB_874/bin/toco_from_protos
    /Users/sachinsingh/miniconda3/envs/NB_874/lib/python3.8/site-packages/tensorflow-2.4.0.dist-info/*
    /Users/sachinsingh/miniconda3/envs/NB_874/lib/python3.8/site-packages/tensorflow/*
Proceed (y/n)? ^C
ERROR: Operation cancelled by user


In [1]:
!pip3 install tensorflow==1.5

ERROR: Could not find a version that satisfies the requirement tensorflow==1.5 (from versions: 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0)
ERROR: No matching distribution found for tensorflow==1.5


In [3]:
dir(graph)

NameError: name 'graph' is not defined